site_name: Test docs
site_description: 'A docs test'
site_author: 'John M. Aiken'
docs_dir: docs/
repo_name: 'SerpRateAI/TigerTail'
repo_url: 'https://serprateai.github.io/TigerTail/'
nav:
    - Home: index.md
theme:
  name: 'material'
plugins:
- search
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    custom_templates: templates
    default_handler: python
    handlers:
      python:
        options:
          show_source: false
