site_name: Test docs
site_description: 'A docs test'
site_author: 'John M. Aiken'
docs_dir: docs/
repo_name: 'SerpRateAI/TigerTail'
repo_url: 'https://serprateai.github.io/TigerTail/'
nav:
    - Home: index.md
theme:
  name: 'material'
