site_name: Test docs
site_description: 'A docs test'
site_author: 'John M. Aiken'
docs_dir: docs/
repo_name: 'SerpRateAI/TigerTail'
repo_url: 'https://serprateai.github.io/TigerTail/'
nav:
    - Home: index.md
    - Reference: reference.md
    - Birthday Gift Example: birthday-gift-example.ipynb
    - Student Example: student-example.ipynb
    - SerpRate AI Example: serprate-ai-example.ipynb
    - Detecting Heavy Drinking Example: detecting-heavy-drinking-example.ipynb
theme:
  name: 'material'
plugins:
- search
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options:
          show_source: false
- mknotebooks
