name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - run: pip install mkdocs-material mkdocstrings[python] mknotebooks
      
      - name: Checkout dev
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: docs/requirements.txt


